export { default as AdvantagesSection } from './homePage/AdvantagesSection/AdvantagesSection.jsx';
export { default as WelcomeSection } from './homePage/WelcomeSection/WelcomeSection.jsx';
export { default as PrivateRoutes } from './routes/PrivateRoutes.jsx';
export { default as RestrictedRoutes } from './routes/RestrictedRoutes.jsx';
export { default as SharedLayout } from './sharedLayout/SharedLayout.jsx';
export { default as Modal } from './modal/Modal/Modal.jsx';
export { default as WaterMainInfo } from './trackerPage/WaterMainInfo/WaterMainInfo.jsx';
export { default as WaterDetailedInfo } from './trackerPage/WaterDetailedInfo/WaterDetailedInfo.jsx';
export { default as Loader } from './loader/Loader.jsx';
